---
- name: Common tasks executed on Debian hosts
  hosts: vm1
  become: yes
  tasks:
    - name: Install my favourite monitoring tool
      apt:
        name: "{{ monitoring_tool | mandatory }}"
        state: latest

- name: Common tasks executed on CentOS hosts
  hosts: vm2
  become: yes
  tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: latest
    - name: Install my favourite monitoring tool
      yum:
        name: "{{ monitoring_tool | mandatory }}"
        state: latest
    - name: Install MOTD
      copy:
        src: motd
        dest: /etc/motd


